name: Debug MIA scan
on: workflow_dispatch
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          sudo apt-get update && sudo apt-get install -y wget moreutils
      - name: Test scan depth=1 + unbuffer + tee
        run: |
          set -euo pipefail
          wget --spider -r -l1 -np -nv -e robots=off https://www.marxists.org/ 2>&1 \
            | awk '/^--/ {print $3}' \
            | grep -v '/$' \
            | stdbuf -oL tee test_urls.txt \
            | while read -r u; do
                echo "🔄 $u"
              done
