name: Copy MIA to Dropbox
on:
  workflow_dispatch:
jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone & wget
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          sudo apt-get update && sudo apt-get install -y wget
      - name: Scan Marxists.org (toutes ressources, streaming)
        run: |
          wget --spider -r -np -nv -e robots=off https://www.marxists.org/ 2>&1 \
            | awk '/^--/ {print $3}' \          # extrait chaque URL découverte  [oai_citation:3‡GitHub](https://github.com/github/vscode-github-actions/issues/126?utm_source=chatgpt.com)
            | grep -v '/$' \                    # conserve tout ce qui n’est pas un répertoire 
            | tee urls.txt \                    # écrit ET affiche chaque URL au fur et à mesure  [oai_citation:4‡Medium](https://mihirpopat.medium.com/monitoring-and-troubleshooting-github-actions-runs-and-logs-613cef9afd01?utm_source=chatgpt.com)
            | sort -u -o urls.txt
      - name: Stream to Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          while read -r u; do
            rclone copyurl "$u" "dropbox:/MIA${u#https://www.marxists.org}" \
              --dropbox-token "$DROPBOX_TOKEN" --auto-filename --no-update-modtime
          done < urls.txt
