name: Copy MIA to Dropbox
on:
  workflow_dispatch:
jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone & wget
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          sudo apt-get update && sudo apt-get install -y wget
      - name: Mirror & Stream all resources
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          set -euo pipefail
          wget --spider -r -np -nv -e robots=off https://www.marxists.org/ 2>&1 \
            | awk '/^--/ {print $3}' \
            | grep -v '/$' \
            | while read -r u; do
                echo "🔄 $u"
                rclone copyurl "$u" "dropbox:/MIA${u#https://www.marxists.org}" \
                  --dropbox-token "$DROPBOX_TOKEN" --auto-filename --no-update-modtime
              done
